config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'items#index'

	resources :charges
	
	resources :users, :path => "egodefou"

	resources :items, :path => "petitminou" do
		resources :join_cart_items
	end 
	resources :join_cart_items
	#resources :sessions, only: [:new, :create, :destroy]
	resources :carts, :path => "donnenoustonargent"
	resources :orders, :path => "mercidenousengraisser"

	#get 'bienvenue', to: 'items#index'
	#get 'petitminou', to: 'items#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
	has_many :join_cart_items
  has_many :items, through: :join_cart_items
  
end

app/models/item.rb
class Item < ApplicationRecord

	has_many :join_cart_items
    has_many :carts, through: :join_cart_items

    # has_many :order_items
    # has_many :orders, through: :order_items
end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :item
  
end

app/models/order.rb
class Order < ApplicationRecord
  # after_create :orderconfirm_send
  
  
  has_many :cart

  belongs_to :user
	#belongs_to :cart
	has_many :order_items
  has_many :items, through: :order_item
  
  private
=begin
  def orderconfirm_send
    OrderMailer.orderconfirm_email(self).deliver_now
    OrderMailer.orderadmin_email(self).deliver_now
  end
=end 

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     
  after_create :welcome_send  
    

  has_one :cart
  has_many :orders 

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
    @items = @cart.items
    
    @amount = 0
    @cart.items.each do |item|
    @amount += item.price
    end 
	end

	def destroy
		@cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private
  def total
    items.sum(&:price)
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @cart = @current_cart
    @items = @cart.items
    
    @amount = 0
    @cart.items.each do |item|
    @amount += item.price

	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount.to_i * 100,
	    description: 'Rails Stripe customer',
	    currency: 'eur',
	  })

	if charge.paid
		@order = Order.create(user: current_user) #(order_params)
    # @order.items = []
    @current_cart.items.each do |item|
      OrderItem.create(item: item, order: @order)
			# item.cart_id = nil
			flash[:success] = "Ton paiement a bien été pris en compte"
    end

    # send emails after creation of Order and OrderItem
    OrderMailer.orderconfirm_email(@order).deliver_now
    OrderMailer.orderadmin_email(@order).deliver_now

    @current_cart.destroy
    session[:cart_id] = nil
    redirect_to user_path(current_user.id), :flash => { :success => "Command confirmed!" }
	end

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
  end
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def destroy
    @cart_item = @current_cart.items(:item_id)
    @item = Item.find(params[:id])
    @cart_item.destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    @order = Order.new
  end

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.create(user: current_user) #(order_params)
    # @order.items = []
    @current_cart.items.each do |item|
      OrderItem.create(item: item, order: @order)
      # item.cart_id = nil
    end

    @current_cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end


	private
	
  def order_params
    params.require(:order) #.permit(:name, :email, :address, :pay_method)
	end
=begin 
	def create
		@order = current_order
		@order_item = @order.order_items.new(order_item_params)
		@order.save
		session[:order_id] = @order.id
	end

	def update
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.update_attributes(order_item_params)
		@order_items = @order.order_items
	end

	def destroy
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.destroy
		@order_items = @order.order_items
	end

	private
		def order_item_params
			params.require(:order_item).permit(:product_id, :quantity)
	end
=end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	# corespond à la page de login

	def new
	end

	# effectue l'hautentification
	def create
	  # cherche s'il existe un utilisateur en base avec l’e-mail
	  @user = User.find_by(email: params[:email])

	  # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
	  if @user && @user.authenticate(params[:encrypted_password])
	    session[:user_id] = @user.id
	    remember @user
	    # redirige où tu veux, avec un flash ou pas
	    redirect_to home_path
	  else
	    flash.now[:danger] = 'Invalid email/password combination'
	    render 'new'
	  end
	end

	# logout
	def destroy
		session.delete(:user_id)
		redirect_to home_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :good_user?, only: [:show, :edit, :update]

	def show
		@user = User.find(params[:id])
		@orders = @user.orders
	end


  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Ton profil a été mis à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :description, :email)
    end

    def good_user?
      if @user != current_user
        flash[:danger] = "You do not have access to other user account"
        redirect_to root_path
      end
end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
		if !session[:cart_id].nil?
			Cart.find(session[:cart_id])
		else
			Cart.new
		end
  end

	def bootstrap_class_for_flash(type)
		case type
			when 'notice' then "alert-info"
			when 'success' then "alert-success"
			when 'error' then "alert-danger"
			when 'alert' then "alert-warning"
		end
	end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/creates_helper.rb
module CreatesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/join_cart_items_helper.rb
module JoinCartItemsHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/new.html.erb
<h1> Coucou c'est le cart ! </h1>

<div class="blogs-3">

                <div class="container">
                    <div class="row">
                        <div class="col-md-10 ml-auto mr-auto">
                            <h2 class="title">Votre panier</h2>
                            <br>
														<%@cart.items.each do |item|%>
                            <div class="card card-plain card-blog">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="card-image">
                                            <img class="img img-raised rounded" src="assets/img/examples/card-blog10.jpg">
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h3 class="card-title">
                                            <a href="#pablo"> <%= @cart.items %>/a>
                                        </h3>
                                        <p class="card-description">
                                            Finding temporary housing for your dog should be as easy as renting an Airbnb. That’s the idea behind Rover, which raised $65 million to expand its pet sitting and dog-walking businesses..
                                            <a href="#pablo"> Read More </a>
                                        </p>
                                        <div class="author">
                                            <img src="assets/img/olivia.jpg" alt="..." class="avatar img-raised">
                                            <span>Katie Roof</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
						
						<% end %>
                
             
            

app/views/carts/show.html.erb
<h1> </h1>

<div class="blogs-3">
<div class="container">
    <div class="row">
      <div class="col-md-10 ml-auto mr-auto">
<h2 class="title">Votre panier</h2>
</div>
</div>
</div>
<%@items.each do |item|%>
  <div class="container">
    <div class="row">
      <div class="col-md-10 ml-auto mr-auto">
        
          <br>
						
							<div class="card card-plain card-blog">
								<div class="row">
									<div class="col-md-4">
										<div class="card-image">
											<img class="img img-raised rounded" src="https://images.pexels.com/photos/171227/pexels-photo-171227.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260">
										</div>
									</div>
									<div class="col-md-8">
										<h3 class="card-title">
											<a href="#pablo"> <%= item.title %></a>
										</h3>
											<p class="card-description">
											<%= item.description %>
											</p>
											<div class="author">
													<p><%= item.price %>€</p>
											</div>
																<div class="row justify-content-end">
				
			</div>
											<div class="row justify-content-end">
				<%= link_to "Supprimer l'article", item_join_cart_item_path(:item_id), method: :delete,  data: { confirm: "Tu es sûr(e) ?" }, class:"btn btn-secondary" %>
			</div>
									</div>
								</div>
							</div>
			</div>
		</div>
	</div>
</div>
<% end %>
<div class="container">
    <div class="row">
      <div class="col-md-10 ml-auto mr-auto">
			<div class="row justify-content-end">
			<p>Total <%= @amount %> €</p>
			</div>
<div class="row justify-content-end">
			<!--	<%= link_to "Passer commande", new_charge_path, method: :get, class:"btn btn-primary" %> -->
				 <% if @amount > 0 %>
								<%= form_tag charges_path do %> 
									<input type="text" name="cart_amount" value="<%= (@amount * 100).round %>" hidden>   

									<script  
										src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
										data-key="<%= ENV['PUBLISHABLE_KEY'] %>"
										data-label="Passer la commande"    
										data-amount="<%= @amount * 100 %>"   
										data-name="E-Kitten"   
										data-description="Votre commande"   
										data-image="https://stripe.com/img/documentation/checkout/marketplace.png"  
										data-locale="auto"  
										data-currency="eur">    
									</script> 


									<% end %>
<% end %>
			</div> 
			</div>
			</div>
			</div>  
             
            

app/views/users/show.html.erb
<head>
    <meta charset="utf-8" />
</head>

<body class="profile-page">
    <div class="wrapper">
        <div class="page-header page-header-small" filter-color="black">
            <div class="page-header-image" data-parallax="true" style="background-image: url('https://wallpapertag.com/wallpaper/full/3/c/3/688665-cute-kitty-backgrounds-1920x1200-ipad-retina.jpg') ;">
            </div>
            <div class="content-center">
                <h3 class="title">Mon Profil</h3>
                <div class="content">
                    <div class="social-description">
                        <h2><%= @user.first_name %> <%= @user.last_name %></h2>
                        <p><%= @user.email %></p>
                        <%= link_to "Éditer mon profil", edit_user_registration_path, method: :get, :class => "btn btn-primary" %>
                    </div>
                </div>
            </div>
        </div>
        <div class="section">
          <div class="container">
          	  <h2 class="title">Mon historique des commandes</h2>   
                <div class="col">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class="">
                                <tr>
                                    <th class="text-center">N°</th>
                                    <th>Date de commande</th>
                                    <th>Articles</th>
                                    <th class="text-center">Prix</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% if @orders != nil %>
                                    <% @orders.each do |order| %>
                                    <tr>
                                        <td class="text-center"><%= order.id %></td>
                                        <td><%= order.created_at %></td>
                                        <td>
                                            <% order.order_items.each do |order_item| %>
                                                <%= order_item.item.title %><br>
                                            <% end %>
                                        </td>
                                      
                                        <td class="text-center">
                                            <% order.order_items.each do |order_item| %>
                                                <%= order_item.item.price %>€<br>
                                            <% end %>
                                        </td> 
                                    </tr>
                                    <% end %> 
                                <% end %>
                            </tbody>
                            </table>
                    </div>
                </div>  
          </div>
        </div>
    </div>
</body>

</html>