config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'items#index'

	resources :charges
	
	resources :users, :path => "egodefou"

	resources :items, :path => "petitminou" do
		resources :join_cart_items
	end 
	resources :join_cart_items
	#resources :sessions, only: [:new, :create, :destroy]
	resources :carts, :path => "donnenoustonargent"
	resources :orders, :path => "mercidenousengraisser"

	#get 'bienvenue', to: 'items#index'
	#get 'petitminou', to: 'items#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
	has_many :join_cart_items
  has_many :items, through: :join_cart_items
  
end

app/models/item.rb
class Item < ApplicationRecord

	has_many :join_cart_items
    has_many :carts, through: :join_cart_items

    # has_many :order_items
    # has_many :orders, through: :order_items
end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :item
  
end

app/models/order.rb
class Order < ApplicationRecord
  # after_create :orderconfirm_send
  
  
  has_many :cart

  belongs_to :user
	#belongs_to :cart
	has_many :order_items
  has_many :items, through: :order_item
  
  private
=begin
  def orderconfirm_send
    OrderMailer.orderconfirm_email(self).deliver_now
    OrderMailer.orderadmin_email(self).deliver_now
  end
=end 

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     
  after_create :welcome_send  
    

  has_one :cart
  has_many :orders 

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/Item/items_controller.rb
class ItemsController < ApplicationController

  def index
  end 
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
    @items = @cart.items
    
    @amount = 0
    @cart.items.each do |item|
    @amount += item.price
    end 
	end

	def destroy
		@cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private
  def total
    items.sum(&:price)
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @cart = @current_cart
    @items = @cart.items
    
    @amount = 0
    @cart.items.each do |item|
    @amount += item.price

	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount.to_i * 100,
	    description: 'Rails Stripe customer',
	    currency: 'eur',
	  })

	if charge.paid
		@order = Order.create(user: current_user) #(order_params)
    # @order.items = []
    @current_cart.items.each do |item|
      OrderItem.create(item: item, order: @order)
			# item.cart_id = nil
			flash[:success] = "Ton paiement a bien été pris en compte"
    end

    # send emails after creation of Order and OrderItem
    OrderMailer.orderconfirm_email(@order).deliver_now
    OrderMailer.orderadmin_email(@order).deliver_now

    @current_cart.destroy
    session[:cart_id] = nil
    redirect_to user_path(current_user.id), :flash => { :success => "Command confirmed!" }
	end

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
  end
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def destroy
    @cart_item = @current_cart.items(:item_id)
    @item = Item.find(params[:id])
    @cart_item.destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    @order = Order.new
  end

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.create(user: current_user) #(order_params)
    # @order.items = []
    @current_cart.items.each do |item|
      OrderItem.create(item: item, order: @order)
      # item.cart_id = nil
    end

    @current_cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end


	private
	
  def order_params
    params.require(:order) #.permit(:name, :email, :address, :pay_method)
	end
=begin 
	def create
		@order = current_order
		@order_item = @order.order_items.new(order_item_params)
		@order.save
		session[:order_id] = @order.id
	end

	def update
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.update_attributes(order_item_params)
		@order_items = @order.order_items
	end

	def destroy
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.destroy
		@order_items = @order.order_items
	end

	private
		def order_item_params
			params.require(:order_item).permit(:product_id, :quantity)
	end
=end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	# corespond à la page de login

	def new
	end

	# effectue l'hautentification
	def create
	  # cherche s'il existe un utilisateur en base avec l’e-mail
	  @user = User.find_by(email: params[:email])

	  # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
	  if @user && @user.authenticate(params[:encrypted_password])
	    session[:user_id] = @user.id
	    remember @user
	    # redirige où tu veux, avec un flash ou pas
	    redirect_to home_path
	  else
	    flash.now[:danger] = 'Invalid email/password combination'
	    render 'new'
	  end
	end

	# logout
	def destroy
		session.delete(:user_id)
		redirect_to home_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :good_user?, only: [:show, :edit, :update]

	def show
		@user = User.find(params[:id])
		@orders = @user.orders
	end


  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Ton profil a été mis à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :description, :email)
    end

    def good_user?
      if @user != current_user
        flash[:danger] = "You do not have access to other user account"
        redirect_to root_path
      end
end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
		if !session[:cart_id].nil?
			Cart.find(session[:cart_id])
		else
			Cart.new
		end
  end

	def bootstrap_class_for_flash(type)
		case type
			when 'notice' then "alert-info"
			when 'success' then "alert-success"
			when 'error' then "alert-danger"
			when 'alert' then "alert-warning"
		end
	end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/creates_helper.rb
module CreatesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/join_cart_items_helper.rb
module JoinCartItemsHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<link rel="stylesheet" href="style.scss">
</head>

<body class="ecommerce-page">

    <div class="wrapper">
        <div id="carouselExampleIndicators" class="carousel slide">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class=""></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item">
                    <div class="page-header header-filter">
                        <div class="page-header-image" style="background-image: url('https://images.pexels.com/photos/416160/pexels-photo-416160.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260');"></div>
                        <div class="content-center text-center">
                            <div class="row">
                                <div class="col-md-8 ml-auto mr-auto2">
                                    <h1 class="title">Les chatons les plus mignons</h1>
                                    <h4 class="description text-white">Des boules de poils trop choupinous</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item active">
                    <div class="page-header header-filter">
                        <div class="page-header-image" style="background-image: url('https://images.pexels.com/photos/39255/cat-favorite-relaxation-rest-39255.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');"></div>
                        <div class="content-center">
                            <div class="row">
                                <div class="col-md-8 ml-auto mr-auto text-center">
                                    <h1 class="title">Les chatons les plus cons</h1>
                                    <h4 class="description text-white">Idiots et rigolos nous les avons tous</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="page-header header-filter">
                        <div class="page-header-image" style="background-image: url('https://images.pexels.com/photos/171227/pexels-photo-171227.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260');"></div>
                        <div class="content-center text-center">
                            <div class="row">
                                <div class="col-md-8 ml-auto mr-auto">
                                    <h1 class="title">Trop Lolilol</h1>
                                    <h4 class="description text-white">HIHIHIHIHIHIHIHIHI (putain c'est con)</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <i class="fas fa-arrow-circle-left fa-5x"></i>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <i class="fas fa-arrow-circle-right fa-5x"></i>
            </a>
        </div>
        <div class="main">
            <div class="section">
                <div class="container">
                    <h2 class="section-title">Tout nos chatons</h2>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="collapse-panel">
                                <div class="card-body">
                                    <div class="card card-refine card-plain">
                                        <h4 class="card-title">
                                            Rechercher
                                            <button class="btn btn-default btn-icon btn-neutral pull-right" rel="tooltip" title="Reset Filter">
                                                <i class="fas fa-search"></i>
                                            </button>
                                        </h4>
                                        <div class="card-header" role="tab" id="headingOne">
                                            <h6 class="mb-0">
                                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                    Prix
                                                    <i class="fas fa-euro-sign"></i>
                                                </a>
                                            </h6>
                                        </div>
                                        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                                            <div class="card-body">
                                                <span id="price-left" class="price-left pull-left" data-currency="&euro;">0</span>
                                                <span id="price-right" class="price-right pull-right" data-currency="&euro;">1000</span>
                                                <div class="clearfix"></div>
                                                <div id="sliderRefine" class="slider slider-refine"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card card-refine card-plain">
                                        <div class="card-header" role="tab" id="headingTwo">
                                            <h6 class="mb-0">
                                                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                    Races
                                                    <i class="fas fa-cat"></i>
                                                </a>
                                            </h6>
                                        </div>
                                        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                                            <div class="card-body">
                                                <div class="checkbox">
                                                    <input id="checkbox1" type="checkbox" checked="">
                                                    <label for="checkbox1">
                                                        Gouttière
                                                    </label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox2" type="checkbox">
                                                    <label for="checkbox2">
                                                        Siamois
                                                    </label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox3" type="checkbox">
                                                    <label for="checkbox3">
                                                        Maine Coon
                                                    </label>
                                                </div>
                                            
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card card-refine card-plain">
                                        <div class="card-header" role="tab" id="headingThree">
                                            <h6 class="mb-0">
                                                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                                    Style
                                                    <i class="fas fa-rainbow"></i>
                                                </a>
                                            </h6>
                                        </div>
                                        <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
                                            <div class="card-body">
                                                <div class="checkbox">
                                                    <input id="checkbox9" type="checkbox">
                                                    <label for="checkbox9">
                                                        Gaudriole
                                                    </label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox10" type="checkbox">
                                                    <label for="checkbox10">
                                                        Chutes
                                                    </label>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="checkbox11" type="checkbox">
                                                    <label for="checkbox11">
                                                        Feu
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="row">

                          <%@items.each do |item|%>
                          <div class="col-lg-4 col-md-6">
                            <div class="card card-product">
                              <div class="card-image">
                                <a href="#">
                                  <img src="https://images.pexels.com/photos/416160/pexels-photo-416160.jpeg?auto=compress&cs=tinysrgb&h=120&w=250" alt="chaton" />
                                </a>
                                </div>
                                <div class="card-body">
                                <a href="#">
                                  <h4 class="card-title"><%= item.title %></h4>
                                </a>
                                <p class="card-subtitle mb-2 text-center">
                                  <%= item.description %>
                                </p>
                                <div class="card-footer">
                                  <div class="price-container">
                                    <span class="price"> <%= item.price %>&euro; </span>
                                  </div>
                                  <button class="btn btn-danger btn-neutral btn-icon btn-round pull-right" rel="tooltip" title="Remove from wishlist" data-placement="left">                                 
                                    <i class="fas fa-heart"></i>
                                  </button>
                                  <center>
                                  <div class="container">
                                  <%= link_to "Voir le produit", item_path(item), class:"btn btn-warning btn-sm " %>
                                  </br></br>
                                  <%= button_to  "Ajouter au panier", join_cart_items_path(:item_id => @item_id), method: :post , class:"btn btn-primary btn-sm" %> 
                                  </div>
                                  </center>
                                </div>
                              </div>
                            </div>
                          </div>
                          <%end%> 
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
  
        <!-- end-main-raised -->
    </div>
</body>
<script type="text/javascript">
    $(document).ready(function() {

        var slider2 = document.getElementById('sliderRefine');

        noUiSlider.create(slider2, {
            start: [42, 880],
            connect: true,
            range: {
                'min': [30],
                'max': [900]
            }
        });

        var limitFieldMin = document.getElementById('price-left');
        var limitFieldMax = document.getElementById('price-right');

        slider2.noUiSlider.on('update', function(values, handle) {
            if (handle) {
                limitFieldMax.innerHTML = $('#price-right').data('currency') + Math.round(values[handle]);
            } else {
                limitFieldMin.innerHTML = $('#price-left').data('currency') + Math.round(values[handle]);
            }
        });
    });
</script>

</html>

app/views/items/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
   
</head>

<body class="product-page">

    <div class="wrapper">
        <div class="page-header page-header-mini">
            <div class="page-header-image" data-parallax="true" style="background-image: url('https://images.pexels.com/photos/416160/pexels-photo-416160.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260') ;">
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-5">
                        <div id="productCarousel" class="carousel slide" data-ride="carousel" data-interval="8000">
                            <ol class="carousel-indicators">
                                <li data-target="#productCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#productCarousel" data-slide-to="1"></li>
                                <li data-target="#productCarousel" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active">
                                    <img class="d-block img-raised" src="https://images.pexels.com/photos/416160/pexels-photo-416160.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260" alt="First slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block img-raised" src="https://images.pexels.com/photos/39255/cat-favorite-relaxation-rest-39255.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="Second slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block img-raised" src="https://images.pexels.com/photos/171227/pexels-photo-171227.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260" alt="Third slide">
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#productCarousel" role="button" data-slide="prev">
                                <button type="button" class="btn btn-primary btn-icon btn-round btn-sm" name="button">
                                    <i class="fas fa-arrow-circle-left fa-2x"></i>
                                </button>
                            </a>
                            <a class="carousel-control-next" href="#productCarousel" role="button" data-slide="next">
                                <button type="button" class="btn btn-primary btn-icon btn-round btn-sm" name="button">
                                    <i class="fas fa-arrow-circle-right fa-2x"></i>
                                </button>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6 ml-auto mr-auto">
                        <h2 class="title"> <%= @item.title %></h2>
                        <h2 class="main-price"> <%= @item.price %>€</h2>
                        <div id="accordion" role="tablist" aria-multiselectable="true" class="card-collapse">
                            <div class="card card-plain">
                                <div class="card-header" role="tab" id="headingOne">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Description
                                        <i class="fas fa-circle"></i>
                                    </a>
                                </div>
                                <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="card-body">
                                        <p> <%= @item.description %></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row pick-size">
                            <div class="col-lg-6 col-md-8 col-sm-6">
                                <label>Select size</label>
                                <select class="selectpicker" data-style="select-with-transition btn btn-block" data-size="7">
                                    <option value="1">Small </option>
                                    <option value="2">Medium</option>
                                    <option value="3">Large</option>
                                </select>
                            </div>
                        </div>
                        <div class="row justify-content-end">
                            <%= button_to  "Ajouter au panier", join_cart_items_path(:item_id => @item.id), method: :post , class: "btn btn-primary mr-3"%>
                        </div>
                    </div>
                </div>
               </body>
</html>