config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'items#index'

	resources :charges
	
	resources :users, :path => "egodefou"

	resources :items, :path => "petitminou" do
		resources :join_cart_items
	end 
	resources :join_cart_items
	#resources :sessions, only: [:new, :create, :destroy]
	resources :carts, :path => "donnenoustonargent"
	resources :orders, :path => "mercidenousengraisser"

	#get 'bienvenue', to: 'items#index'
	#get 'petitminou', to: 'items#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
	has_many :join_cart_items
  has_many :items, through: :join_cart_items
  
end

app/models/item.rb
class Item < ApplicationRecord

	has_many :join_cart_items
    has_many :carts, through: :join_cart_items

    # has_many :order_items
    # has_many :orders, through: :order_items
end

app/models/join_cart_item.rb
class JoinCartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :item
  
end

app/models/order.rb
class Order < ApplicationRecord
  # after_create :orderconfirm_send
  
  
  has_many :cart

  belongs_to :user
	#belongs_to :cart
	has_many :order_items
  has_many :items, through: :order_item
  
  private
=begin
  def orderconfirm_send
    OrderMailer.orderconfirm_email(self).deliver_now
    OrderMailer.orderadmin_email(self).deliver_now
  end
=end 

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     
  after_create :welcome_send  
    

  has_one :cart
  has_many :orders 

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
    @items = @cart.items
    
    @amount = 0
    @cart.items.each do |item|
    @amount += item.price
    end 
	end

	def destroy
		@cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private
  def total
    items.sum(&:price)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def destroy
    @cart_item = @current_cart.items(:item_id)
    @item = Item.find(params[:id])
    @cart_item.destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    @order = Order.new
  end

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.create(user: current_user) #(order_params)
    # @order.items = []
    @current_cart.items.each do |item|
      OrderItem.create(item: item, order: @order)
      # item.cart_id = nil
    end

    @current_cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end


	private
	
  def order_params
    params.require(:order) #.permit(:name, :email, :address, :pay_method)
	end
=begin 
	def create
		@order = current_order
		@order_item = @order.order_items.new(order_item_params)
		@order.save
		session[:order_id] = @order.id
	end

	def update
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.update_attributes(order_item_params)
		@order_items = @order.order_items
	end

	def destroy
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.destroy
		@order_items = @order.order_items
	end

	private
		def order_item_params
			params.require(:order_item).permit(:product_id, :quantity)
	end
=end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :good_user?, only: [:show, :edit, :update]

	def show
		@user = User.find(params[:id])
		@orders = @user.orders
	end


  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Ton profil a été mis à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :description, :email)
    end

    def good_user?
      if @user != current_user
        flash[:danger] = "You do not have access to other user account"
        redirect_to root_path
      end
end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
		if !session[:cart_id].nil?
			Cart.find(session[:cart_id])
		else
			Cart.new
		end
  end

	def bootstrap_class_for_flash(type)
		case type
			when 'notice' then "alert-info"
			when 'success' then "alert-success"
			when 'error' then "alert-danger"
			when 'alert' then "alert-warning"
		end
	end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/creates_helper.rb
module CreatesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eboutique</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="turbolinks-visit-control" content="reload">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!--     CSS files     -->
    <link href="./assets/css/bootstrap.min.scss" rel="stylesheet" />
    <link href="./assets/css/now-ui-kit.scss?v=1.2.0" rel="stylesheet" />


  </head>

  <body class="ecommerce-page">
      <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-white fixed-top navbar-transparent" color-on-scroll="500">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="/" rel="tooltip" title="Back to Home" data-placement="bottom">
                    E-Kitten
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" data-nav-image="../assets/img/blurred-image-1.jpg" data-color="orange">
                <ul class="navbar-nav ml-auto">
              <div class="collapse navbar-collapse" data-nav-image="../assets/img/blurred-image-1.jpg" data-color="orange">
        
          <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">    
            <% if user_signed_in? %>
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.first_name != nil %>
                  <%= current_user.first_name %>
                <% else %>
                  Mon compte
                <% end %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                	<%= link_to "Mon Panier", cart_path(current_cart), :class => "dropdown-item" %>
									<%= link_to "Mon Profil", user_path(current_user), :class => "dropdown-item" %>
                	<%= link_to "Éditer mon profil", edit_user_registration_path, :class => "dropdown-item" %>
                  <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete,  data: { confirm: "Tu es sûr(e) ?" }, :class => "dropdown-item" %>
                </div>
							</div>
									<% else %>
										<div class="nav-item dropdown">
											<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
												Connexion
											</a>
											<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
												<%= link_to "Se Connecter", new_user_session_path, :class => "dropdown-item" %>
												<%= link_to "S'inscrire", new_user_registration_path, :class => "dropdown-item" %>
											</div>
										</div>
									<% end %>
								</div>
                  </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
                            <i class="fas fa-cat" aria-hidden="true"></i>
                            <p>Chatons</p>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">
                                <i class="now-ui-icons shopping_box"></i> Mignon
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="now-ui-icons ui-2_settings-90"></i> Gros
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="now-ui-icons text_align-left"></i> Petit
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="now-ui-icons sport_user-run"></i> LolCat
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
                            <i class="fas fa-cogs" aria-hidden="true"></i>
                            <p>Paramètres</p>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">
                                <i class="now-ui-icons business_bulb-63"></i> About-us
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="now-ui-icons text_align-left"></i> Contact
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="now-ui-icons design_bullet-list-67"></i> Infos
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->

    

    <%= yield %>

    <!--   Core JS Files   -->

<script type="text/javascript">
    $(document).ready(function() {
        // the body of this function is in assets/js/now-ui-kit.js
        nowuiKit.initSliders();
    });
</script>

  </body>

  <footer class="footer ">
            <div class="container">
                <nav>
                    <ul>
                        <li>
                            <a href="#creative">
                                Locust Devs
                            </a>
                        </li>
                        <li>
                            <a href="#creative">
                                About Us
                            </a>
                        </li>
                        <li>
                            <a href="#creative">
                                Blog
                            </a>
                        </li>
                        <li>
                            <a href="#creative">
                                License
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>, Designed by
                    <a href="#">Locust</a>. Coded by
                    <a href="#">Steph, Tanguy, Jack, Djémil et Paul</a>.
                </div>
            </div>
        </footer>
</html>